### ISSUE TITLE
HTTP/1.1 401 Unauthorized

### ISSUE THREAD

**Issue by esalitrynskiy** [QIWI-API/bill-payments-php-sdk#11]
```
$QIWI_SECRET_KEY = env('QIWI_SECRET_KEY') ;
            $billPayments = new BillPayments($QIWI_SECRET_KEY);
            $billPayments->key = $QIWI_SECRET_KEY;
            $billId = $billPayments->generateId();

            $fields = [
                'amount' => round($price + $delivery_price,2),
                'currency' => 'RUB',
                'phone' => $form['phone'],
                'comment' => 'Заказ №"' . $order->id . '"',
                'expirationDateTime' => (new \DateTime(date("Y-m-d H:i:s")))->modify('+7 day')->format('c'),
            ];

            /** @var \Qiwi\Api\BillPayments $billPayments */
            $response = $billPayments->createBill($billId, $fields);

```

Пытаюсь создать счет на оплату таким образом, абсолютно этот же код работает в простом php файле. Сейчас делаю это в Laravel. Секретный ключ точно есть и передается.

Выдает ошибку "HTTP/1.1 401 Unauthorized" в /vendor/qiwi/bill-payments-php-sdk/src/BillPayments.php:592

Trace ведет на строку 463.

Может ли это быть связано с тем что я сейчас тестирую на другом домене(на том же сервере)?

**Comment by esalitrynskiy** [comment]
В конце ключа не подтягивалось "==" из конфигурации.

**Comment by almaziphone** [comment]
> В конце ключа не подтягивалось "==" из конфигурации.

Можно плз по подробней! Такая же трабла!
