### ISSUE TITLE
HTTP/2 401

### ISSUE THREAD

**Issue by QuietAko** [QIWI-API/bill-payments-php-sdk#19]
$billId = '772'
$billPayments = new \Qiwi\Api\BillPayments(self::SECRET_KEY);
$response = $billPayments->getBillInfo($billId);

return $response;

При обработке получаю ошибку 
HTTP/2 401

**Comment by medovi40k** [comment]
Как пофиксил?

**Comment by QuietAko** [comment]
> Как пофиксил?

у меня был неправильный публичный и приватный ключ вставлен

**Comment by medovi40k** [comment]
Спасибо
