### ISSUE TITLE
Ошибка оплаты

### ISSUE THREAD

**Issue by anonymous33rus** [QIWI-API/bill-payments-php-sdk#5]
Привет, сделал форму для оплаты 

`

$billPayments = new Qiwi(SECRET_KEY);

        $billId = $billPayments->generateId();

        $params = [

            'billId' => $billId,

            'publicKey' => PUBLIC_KEY,

            'amount' => 1,

            'successUrl' => route('checkout-qiwi', ['billId' => $billId])

        ];

        $link = $billPayments->createPaymentForm($params);

        echo "<a href=".$link.">test</a>";`

Перехожу по ссылке, ввожу данные карты, мне выдает ошибку "Операция отклонена", хотя до этого 2 раза нормально оплатилось, что случилось ?

**Comment by Jamaska** [comment]
Ошибка связанна именно с картой к библиотеке это не имеет отношения.
Для более детального разбора , напишите на cms@qiwi.com
