### ISSUE TITLE
 Qiwi \ Api \ BillPaymentsException (400) HTTP/1.1 400 Bad Request

### ISSUE THREAD

**Issue by dulingleb** [QIWI-API/bill-payments-php-sdk#6]
При попытке выставить счет, выдается эта ошибка. Не могу понять в чем проблема. Laravel
```
        $billPayments = new \Qiwi\Api\BillPayments(secret_key);

        $billId = $billPayments->generateId();
        $fields = [
            'amount' => '100',
            'currency' => 'RUB',
            'comment' => 'test',
            'expirationDateTime' => '2019-05-05T08:44:07',
            'account' => 'Aleksandr-...',
            'successUrl' => 'http://test.com/',
        ];

        $response = $billPayments->createBill($billId, $fields);
```

**Comment by dulingleb** [comment]
Разобрался.
'expirationDateTime' => '2019-05-05T08:44:07' - тут обязательно надо указывать часовой пояс. Исправьте, пожалуйста, в примере.

**Comment by lar-dragon** [comment]
Для генерации `expirationDateTime` в правильном формате можно воспользоваться функцией `\Qiwi\Api\BillPayments::getLifetimeByDay`. За подробным описанием форматов данных стоит обратиться к (документации протокола](https://developer.qiwi.com/ru/bill-payments/), так как она может изменяться.
